auth:
  authentication:
    scopes:  {}
    tokenUrl:  "http://192.168.240.3:8080/auth/realms/kcrealm/protocol/openid-connect/token"
    publicCerts: []
    username_claim: "sub"
ssh_credentials:
  type: "SSHService"
  url: "http://192.168.240.20:5000"
  max_connections: 500
clusters:
- name: "cluster-SLURM-api"
  ssh:
    host: "192.168.240.2"
    port: 22
    max_clients: 500
  scheduler:
    type: "slurm"
    version: "24.11.0"
    api_url: "http://192.168.240.2:6820"
    api_version: "0.0.42"
    timeout: 10
  service_account:
    client_id: "firecrest-api"
    secret: ""
  probing:
    interval: 60
    timeout: 5
  datatransfer_jobs_directives:
    - "#SBATCH --nodes=1"
    - "#SBATCH --time=0-00:15:00"
    - "#SBATCH --account={account}"
  file_systems:
    - path: '/home'
      data_type: 'users'
      default_work_dir: true
- name: "cluster-SLURM-ssh"
  ssh:
    host: "192.168.240.2"
    port: 22
    max_clients: 500
  scheduler:
    type: "slurm"
    version: "24.11.0"
    timeout: 10
  service_account:
    client_id: "firecrest-api"
    secret: ""
  probing:
    interval: 60
    timeout: 10
  datatransfer_jobs_directives:
    - "#SBATCH --nodes=1"
    - "#SBATCH --time=0-00:15:00"
  file_systems:
    - path: '/home'
      data_type: 'users'
      default_work_dir: true
- name: "cluster-pbs"
  ssh:
    host: "192.168.240.2"
    port: 22
    max_clients: 500
  scheduler:
    type: "pbs"
    version: "23.06.06"
    timeout: 10
  service_account:
    client_id: "firecrest-api"
    secret: ""
  probing:
    interval: 60
    timeout: 10
  datatransfer_jobs_directives:
    - "#PBS -l nodes=1:ppn=1"
    - "#PBS -l walltime=00:15:00"
  file_systems:
    - path: '/home'
      data_type: 'users'
      default_work_dir: true
data_operation:
  max_ops_file_size: 1048576 # 1M
  data_transfer:
    name: "s3-storage"
    service_type: "s3"
    private_url: "http://192.168.240.19:9000"
    public_url: "http://localhost:9000"
    access_key_id: "storage_access_key"
    secret_access_key: ""
    region: "us-east-1"
    ttl: 604800
    multipart:
      use_split: false
      max_part_size: 1073741824 # 1G
      parallel_runs: 3
      tmp_folder: "tmp"
    probing:
      interval: 60
      timeout: 10