site_name: FirecREST v2 Documentation

# provide a link to the docs in top RHS corner
repo_url: https://github.com/eth-cscs/firecrest-v2/
# provide a link to "edit this page" to each page
edit_uri: edit/master/docs/

nav:
  - Welcome: README.md
  - 'Getting started':
    - getting_started/README.md
  - Setup: 
    - 'Architecture':
      - setup/arch/README.md
      - 'Systems':
        - setup/arch/systems/README.md
      - 'Authentication and authorization':
        - setup/arch/auth/README.md
    - 'Configuration':
      - setup/conf/README.md
    - 'Deployment':
      - setup/deploy/README.md 
  - 'User guide':
    - user_guide/README.md
  - 'Use cases':
    - use_cases/README.md
  - 'API Reference': https://eth-cscs.github.io/firecrest-v2/openapi/
   
theme:
  name: material
  language: en
  features:
    - content.code.copy
    # add an "edit this page" icon on each page
    - content.action.edit
    - navigation.indexes
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
  icon:
    # set the icon for "edit this page"
    edit: material/pencil
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/img/firecrest-logo.gif
  favicon: assets/img/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      pipeline:
        - trimmer
  - autorefs

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  # for captioning images
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css