# Copyright (c) 2025, ETH Zurich. All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

import contextvars
import json
import re
import uuid
import logging

from fastapi import Request

# # configs
# from firecrest import config
# from firecrest.plugins import settings as plugin_settings

# Trace ID is autmatically generated with any Request
tracing_id = contextvars.ContextVar("tracing_id", default=str(uuid.uuid4()))
# Tracing data are generated by the middleware and collect general information about the processing Request
tracing_data = contextvars.ContextVar("tracing_data", default='{}')
# The actual tracing logger
tracing_logger = logging.getLogger("f7t_v2_tracing_log")


def get_log_traceid():
    return tracing_id.get()


def set_tracing_data(request_url: str, route_name: str, method: str):
    system = ""

    # if match := re.search(
    #     r"^\/([^\/\s]+)\/([^\/\s]+)\/(.*)$",
    #     request_url,
    #     re.IGNORECASE,
    # ):
    #     router = match.group(1)
    #     system = match.group(2)
    #     method = match.group(3)

    tracing_data.set(json.dumps(
        {
            "system_name": system,
            "route": route_name,
            "method": method,
            "endpoint": request_url
        })
    )


def tracing_log_middleware(request: Request, username: str, status_code: int):
    log_data = json.loads(tracing_data.get())
    log_data["trace_id"] = get_log_traceid()
    log_data["username"] = username
    log_data["status_code"] = status_code
    log_data["base_url"] = request.base_url
    log_data["user_agent"] = request.headers['user-agent']
    log_data["path"] = request.scope['path']
    log_data["root_path"] = request.scope['root_path']
    log_data["components"] = request.url.components[2]
    log_data["scheme"] = request.url.scheme
    tracing_logger.info(log_data)


def tracing_log_command(username, command_action, exit_status, command=""):

    # Load f7t_v2_tracing_log data
    traced_data = json.loads(tracing_data.get())
    if traced_data:      
        # Log data packet
        log_data = {
            "trace_id": get_log_traceid(),
            "username": username,
            "microservice": traced_data['router'],
            "machinename": traced_data['system_name'],
            "message": command_action,
            "command" : command,
            "exit_status": exit_status
        }
        tracing_logger.info(log_data)
