name: Publish Helm Chart

on:
  release:
    types: [prereleased, released]


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # this additional step is done since the chart-releaser-action doesn't take 
    # correctly the release name, and then it doesn't create a new helm release    
    - name: Custom packaging
      run: |
        # obtain the version for the Chart from the release
        VERSION=${{ github.ref_name }}
        # 
        rm -rf .cr-release-packages
        mkdir -p .cr-release-packages
        helm package build/helm/firecrest-api --app-version=$VERSION --version=$VERSION --destination=.cr-release-packages

    - name: Setup Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: build/helm
        pages_branch: gh-pages
        skip_packaging: true
      env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
