name: Test FirecREST v2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  static_analysis:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install Static Analysis Tools
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r ./requirements-static-code.txt
    - name: Run Static Code Analysis
      run: |
        source venv/bin/activate
        ruff check ./src
        bandit -ll -r --exclude venv ./src
